export const SET_REPOS = "SET_REPOS";
export const SEARCHING_REPOS = "SEARCHING_REPOS";

export const ADD_BOOKMARK = "ADD_BOOKMARK";
export const DEL_BOOKMARK = "DEL_BOOKMARK";
export const POPULATE_BOOKMARKS = "POPULATE_BOOKMARKS";
