export const SET_REPOS = "SET_REPOS";
export const SEARCHING_REPOS = "SEARCHING_REPOS";

export const ADD_BOOKMARK = "ADD_BOOKMARK";
export const ADDING_BOOKMARK = "ADDING_BOOKMARK";
export const REMOVE_BOOKMARK = "REMOVE_BOOKMARK";
export const DELETING_BOOKMARK = "DELETING_BOOKMARK";
export const POPULATE_BOOKMARKS = "POPULATE_BOOKMARKS";
export const GETTING_BOOKMARKS = "GETTING_BOOKMARKS";
